/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prashant
 */
public class Eco_Bikes extends javax.swing.JFrame {

    ImageIcon eko_bikes_icon = new ImageIcon("bike_icon.png");

    /**
     * Creates new form Eco_Bikes
     */
    public Eco_Bikes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentpanel_buttongroup = new javax.swing.ButtonGroup();
        biketypes_buttongroup = new javax.swing.ButtonGroup();
        background_panel = new javax.swing.JPanel();
        content_panel = new javax.swing.JPanel();
        table_panel = new javax.swing.JPanel();
        export_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        categorysearch_cb = new javax.swing.JComboBox<>();
        searchprice_textfield = new javax.swing.JTextField();
        pricesearch_button = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        current_records_table = new javax.swing.JTable();
        images_panel = new javax.swing.JPanel();
        bmx_radiobutton = new javax.swing.JRadioButton();
        city_radiobutton = new javax.swing.JRadioButton();
        enduro_radiobutton = new javax.swing.JRadioButton();
        hardtail_radiobutton = new javax.swing.JRadioButton();
        kids_radiobutton = new javax.swing.JRadioButton();
        title_label = new javax.swing.JLabel();
        bikeinfo_panel = new javax.swing.JPanel();
        bmx_panel = new javax.swing.JPanel();
        bmximage_label = new javax.swing.JLabel();
        bmxdescription_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        city_panel = new javax.swing.JPanel();
        cityimage_label = new javax.swing.JLabel();
        citydescription_label = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        enduro_panel = new javax.swing.JPanel();
        enduroimage_label = new javax.swing.JLabel();
        endurodescription_label = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        hardtail_panel = new javax.swing.JPanel();
        hardtailimage_label = new javax.swing.JLabel();
        hardtaildescription_label = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        kids_panel = new javax.swing.JPanel();
        kidsimage_label = new javax.swing.JLabel();
        kidsdescription_label = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        navigation_panel = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        category_label = new javax.swing.JLabel();
        brand_label = new javax.swing.JLabel();
        price_label = new javax.swing.JLabel();
        material_label = new javax.swing.JLabel();
        id_tf = new javax.swing.JTextField();
        modelname_tf = new javax.swing.JTextField();
        price_tf = new javax.swing.JTextField();
        brand_tf = new javax.swing.JTextField();
        addbike_button = new javax.swing.JButton();
        or_label = new javax.swing.JLabel();
        importbulk_button = new javax.swing.JButton();
        category_cb = new javax.swing.JComboBox<>();
        material_cb = new javax.swing.JComboBox<>();
        logo_label = new javax.swing.JLabel();
        table_radiobutton = new javax.swing.JRadioButton();
        image_radiobutton = new javax.swing.JRadioButton();
        menu_bar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        open_file_item = new javax.swing.JMenuItem();
        exit_file_item = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        programguide_item = new javax.swing.JMenuItem();
        contact_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eco Bikes Information System");
        setName("main_frame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 700));

        background_panel.setBackground(new java.awt.Color(44, 44, 44));
        background_panel.setMaximumSize(new java.awt.Dimension(1024, 700));
        background_panel.setPreferredSize(new java.awt.Dimension(1024, 700));

        content_panel.setBackground(new java.awt.Color(44, 44, 44));
        content_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        content_panel.setMaximumSize(new java.awt.Dimension(640, 624));
        content_panel.setLayout(new java.awt.CardLayout());

        table_panel.setBackground(new java.awt.Color(44, 44, 44));
        table_panel.setMaximumSize(new java.awt.Dimension(640, 624));

        export_button.setBackground(new java.awt.Color(44, 44, 44));
        export_button.setForeground(new java.awt.Color(102, 255, 105));
        export_button.setText("Export");
        export_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(44, 44, 44));
        delete_button.setForeground(new java.awt.Color(102, 255, 105));
        delete_button.setText("Erase Records");
        delete_button.setActionCommand("");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        categorysearch_cb.setForeground(new java.awt.Color(255, 255, 255));
        categorysearch_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Bikes", "BMX", "City", "Enduro", "Hardtail", "Kids" }));
        categorysearch_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorysearch_cbActionPerformed(evt);
            }
        });

        searchprice_textfield.setBackground(new java.awt.Color(255, 255, 255));
        searchprice_textfield.setForeground(new java.awt.Color(0, 0, 0));
        searchprice_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchprice_textfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchprice_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchprice_textfieldActionPerformed(evt);
            }
        });
        searchprice_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchprice_textfieldKeyPressed(evt);
            }
        });

        pricesearch_button.setBackground(new java.awt.Color(44, 44, 44));
        pricesearch_button.setForeground(new java.awt.Color(255, 255, 255));
        pricesearch_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        pricesearch_button.setBorder(null);
        pricesearch_button.setOpaque(true);
        pricesearch_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricesearch_buttonActionPerformed(evt);
            }
        });

        current_records_table.setBackground(new java.awt.Color(44, 44, 44));
        current_records_table.setForeground(new java.awt.Color(255, 255, 255));
        current_records_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Model Name", "Category", "Brand", "Price", "Material"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        openFile(System.getProperty("user.dir") + "//src//current_records.csv");
        current_records_table.setGridColor(new java.awt.Color(44, 44, 44));
        current_records_table.setSelectionBackground(new java.awt.Color(0, 0, 0));
        current_records_table.setSelectionForeground(new java.awt.Color(102, 255, 105));
        jScrollPane7.setViewportView(current_records_table);
        if (current_records_table.getColumnModel().getColumnCount() > 0) {
            current_records_table.getColumnModel().getColumn(0).setResizable(false);
            current_records_table.getColumnModel().getColumn(1).setResizable(false);
            current_records_table.getColumnModel().getColumn(2).setResizable(false);
            current_records_table.getColumnModel().getColumn(3).setResizable(false);
            current_records_table.getColumnModel().getColumn(4).setResizable(false);
            current_records_table.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout table_panelLayout = new javax.swing.GroupLayout(table_panel);
        table_panel.setLayout(table_panelLayout);
        table_panelLayout.setHorizontalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_panelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(export_button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_button)
                .addGap(49, 49, 49))
            .addGroup(table_panelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(categorysearch_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(searchprice_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricesearch_button)
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        table_panelLayout.setVerticalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricesearch_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categorysearch_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchprice_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(export_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        content_panel.add(table_panel, "card2");

        images_panel.setBackground(new java.awt.Color(44, 44, 44));
        images_panel.setForeground(new java.awt.Color(102, 255, 105));
        images_panel.setMaximumSize(new java.awt.Dimension(640, 624));
        images_panel.setPreferredSize(new java.awt.Dimension(640, 624));

        bmx_radiobutton.setBackground(new java.awt.Color(44, 44, 44));
        biketypes_buttongroup.add(bmx_radiobutton);
        bmx_radiobutton.setForeground(new java.awt.Color(102, 255, 105));
        bmx_radiobutton.setSelected(true);
        bmx_radiobutton.setText("BMX Bike");
        bmx_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmx_radiobuttonActionPerformed(evt);
            }
        });

        city_radiobutton.setBackground(new java.awt.Color(44, 44, 44));
        biketypes_buttongroup.add(city_radiobutton);
        city_radiobutton.setForeground(new java.awt.Color(102, 255, 105));
        city_radiobutton.setText("City Bike");
        city_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_radiobuttonActionPerformed(evt);
            }
        });

        enduro_radiobutton.setBackground(new java.awt.Color(44, 44, 44));
        biketypes_buttongroup.add(enduro_radiobutton);
        enduro_radiobutton.setForeground(new java.awt.Color(102, 255, 105));
        enduro_radiobutton.setText("Enduro Bike");
        enduro_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enduro_radiobuttonActionPerformed(evt);
            }
        });

        hardtail_radiobutton.setBackground(new java.awt.Color(44, 44, 44));
        biketypes_buttongroup.add(hardtail_radiobutton);
        hardtail_radiobutton.setForeground(new java.awt.Color(102, 255, 105));
        hardtail_radiobutton.setText("Hardtail Bike");
        hardtail_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardtail_radiobuttonActionPerformed(evt);
            }
        });

        kids_radiobutton.setBackground(new java.awt.Color(44, 44, 44));
        biketypes_buttongroup.add(kids_radiobutton);
        kids_radiobutton.setForeground(new java.awt.Color(102, 255, 105));
        kids_radiobutton.setText("Kids Bike");
        kids_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kids_radiobuttonActionPerformed(evt);
            }
        });

        title_label.setBackground(new java.awt.Color(44, 44, 44));
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("View information of:");

        bikeinfo_panel.setBackground(new java.awt.Color(44, 44, 44));
        bikeinfo_panel.setLayout(new java.awt.CardLayout());

        bmx_panel.setBackground(new java.awt.Color(44, 44, 44));

        bmximage_label.setBackground(new java.awt.Color(255, 255, 255));
        bmximage_label.setForeground(new java.awt.Color(255, 255, 255));
        bmximage_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bmximage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmx.png"))); // NOI18N

        bmxdescription_label.setBackground(new java.awt.Color(44, 44, 44));
        bmxdescription_label.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        bmxdescription_label.setForeground(new java.awt.Color(102, 255, 105));
        bmxdescription_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bmxdescription_label.setText("BMX Description");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 44, 44)));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(44, 44, 44));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Purpose: Stunts and Sport\n2. Braking System: None\n3. Available Materials: Steel, Carbon Fibre, Aluminium\n4. Tyre: Both tube and tubeless available\n5. Suspensions: None\n6. Handle Type: Cruiser Bar");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout bmx_panelLayout = new javax.swing.GroupLayout(bmx_panel);
        bmx_panel.setLayout(bmx_panelLayout);
        bmx_panelLayout.setHorizontalGroup(
            bmx_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bmx_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(bmx_panelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(bmxdescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(bmximage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bmx_panelLayout.setVerticalGroup(
            bmx_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bmx_panelLayout.createSequentialGroup()
                .addComponent(bmximage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bmxdescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bikeinfo_panel.add(bmx_panel, "card2");

        city_panel.setBackground(new java.awt.Color(44, 44, 44));

        cityimage_label.setBackground(new java.awt.Color(255, 255, 255));
        cityimage_label.setForeground(new java.awt.Color(255, 255, 255));
        cityimage_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cityimage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/city.png"))); // NOI18N

        citydescription_label.setBackground(new java.awt.Color(44, 44, 44));
        citydescription_label.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        citydescription_label.setForeground(new java.awt.Color(102, 255, 105));
        citydescription_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        citydescription_label.setText("City Bike Description");

        jScrollPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 44, 44)));

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(44, 44, 44));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea6.setRows(5);
        jTextArea6.setText("1. Purpose: City/Urban commute\n2. Braking System: Calliper braking\n3. Available Materials: Stainless Steel, Alloy, Aluminium\n4. Tyre: Tube\n5. Suspensions: None\n6. Handlebar Type: Cruiser bars");
        jTextArea6.setBorder(null);
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout city_panelLayout = new javax.swing.GroupLayout(city_panel);
        city_panel.setLayout(city_panelLayout);
        city_panelLayout.setHorizontalGroup(
            city_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, city_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(cityimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(city_panelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(citydescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        city_panelLayout.setVerticalGroup(
            city_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(city_panelLayout.createSequentialGroup()
                .addComponent(cityimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(citydescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bikeinfo_panel.add(city_panel, "card2");

        enduro_panel.setBackground(new java.awt.Color(44, 44, 44));

        enduroimage_label.setBackground(new java.awt.Color(255, 255, 255));
        enduroimage_label.setForeground(new java.awt.Color(255, 255, 255));
        enduroimage_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enduroimage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enduro.png"))); // NOI18N

        endurodescription_label.setBackground(new java.awt.Color(44, 44, 44));
        endurodescription_label.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        endurodescription_label.setForeground(new java.awt.Color(102, 255, 105));
        endurodescription_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endurodescription_label.setText("Enduro Description");

        jScrollPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 44, 44)));

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(44, 44, 44));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea7.setRows(5);
        jTextArea7.setText("1. Purpose: For trails, rough terrains, downhill, jumps\n2. Braking System: Disc braking\n3. Available Materials: Carbon Fibre, Alloy\n4. Tyre: Tubeless\n5. Suspensions: Both front and back suspensions (air or hydrolic)\n6. Handlebar Type: Raised or Flat bars");
        jTextArea7.setBorder(null);
        jScrollPane8.setViewportView(jTextArea7);

        javax.swing.GroupLayout enduro_panelLayout = new javax.swing.GroupLayout(enduro_panel);
        enduro_panel.setLayout(enduro_panelLayout);
        enduro_panelLayout.setHorizontalGroup(
            enduro_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enduro_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(enduroimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(enduro_panelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(endurodescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enduro_panelLayout.setVerticalGroup(
            enduro_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enduro_panelLayout.createSequentialGroup()
                .addComponent(enduroimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endurodescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bikeinfo_panel.add(enduro_panel, "card2");

        hardtail_panel.setBackground(new java.awt.Color(44, 44, 44));

        hardtailimage_label.setBackground(new java.awt.Color(255, 255, 255));
        hardtailimage_label.setForeground(new java.awt.Color(255, 255, 255));
        hardtailimage_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardtailimage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardtail.png"))); // NOI18N

        hardtaildescription_label.setBackground(new java.awt.Color(44, 44, 44));
        hardtaildescription_label.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        hardtaildescription_label.setForeground(new java.awt.Color(102, 255, 105));
        hardtaildescription_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardtaildescription_label.setText("Hardtail Description");

        jScrollPane9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 44, 44)));

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(44, 44, 44));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea8.setRows(5);
        jTextArea8.setText("1. Purpose: For hybrid uses like commute, decent trails\n2. Braking System: Disc braking\n3. Available Materials: Carbon Fibre, Alloy, Aluminium\n4. Tyre: Tubeless or Tube\n5. Suspensions: Only front suspension (spring or hydrolic or air)\n6. Handlebar Type: Raised or Flat bars");
        jTextArea8.setBorder(null);
        jScrollPane9.setViewportView(jTextArea8);

        javax.swing.GroupLayout hardtail_panelLayout = new javax.swing.GroupLayout(hardtail_panel);
        hardtail_panel.setLayout(hardtail_panelLayout);
        hardtail_panelLayout.setHorizontalGroup(
            hardtail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hardtail_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(hardtailimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(hardtail_panelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(hardtaildescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hardtail_panelLayout.setVerticalGroup(
            hardtail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hardtail_panelLayout.createSequentialGroup()
                .addComponent(hardtailimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardtaildescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bikeinfo_panel.add(hardtail_panel, "card2");

        kids_panel.setBackground(new java.awt.Color(44, 44, 44));

        kidsimage_label.setBackground(new java.awt.Color(255, 255, 255));
        kidsimage_label.setForeground(new java.awt.Color(255, 255, 255));
        kidsimage_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kidsimage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kids.png"))); // NOI18N

        kidsdescription_label.setBackground(new java.awt.Color(44, 44, 44));
        kidsdescription_label.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        kidsdescription_label.setForeground(new java.awt.Color(102, 255, 105));
        kidsdescription_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kidsdescription_label.setText("Kids Bike Description");

        jScrollPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 44, 44)));

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(44, 44, 44));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea9.setRows(5);
        jTextArea9.setText("1. Purpose: Play, Fun for kids\n2. Braking System: Calliper braking\n3. Available Materials: Stainless Steel, Aluminium\n4. Tyre: Tubeless\n5. Suspensions: None\n6. Handlebar Type: Flat bars");
        jTextArea9.setBorder(null);
        jScrollPane10.setViewportView(jTextArea9);

        javax.swing.GroupLayout kids_panelLayout = new javax.swing.GroupLayout(kids_panel);
        kids_panel.setLayout(kids_panelLayout);
        kids_panelLayout.setHorizontalGroup(
            kids_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kids_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(kidsimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kids_panelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(kidsdescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kids_panelLayout.setVerticalGroup(
            kids_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kids_panelLayout.createSequentialGroup()
                .addComponent(kidsimage_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kidsdescription_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bikeinfo_panel.add(kids_panel, "card2");

        javax.swing.GroupLayout images_panelLayout = new javax.swing.GroupLayout(images_panel);
        images_panel.setLayout(images_panelLayout);
        images_panelLayout.setHorizontalGroup(
            images_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(images_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(bmx_radiobutton)
                .addGap(35, 35, 35)
                .addComponent(city_radiobutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(images_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(images_panelLayout.createSequentialGroup()
                        .addComponent(enduro_radiobutton)
                        .addGap(35, 35, 35)
                        .addComponent(hardtail_radiobutton)
                        .addGap(35, 35, 35)
                        .addComponent(kids_radiobutton)))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, images_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bikeinfo_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        images_panelLayout.setVerticalGroup(
            images_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(images_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(images_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmx_radiobutton)
                    .addComponent(city_radiobutton)
                    .addComponent(enduro_radiobutton)
                    .addComponent(hardtail_radiobutton)
                    .addComponent(kids_radiobutton))
                .addGap(18, 18, 18)
                .addComponent(bikeinfo_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        content_panel.add(images_panel, "card2");

        navigation_panel.setBackground(new java.awt.Color(44, 44, 44));
        navigation_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add new record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        navigation_panel.setPreferredSize(new java.awt.Dimension(200, 243));

        name_label.setBackground(new java.awt.Color(44, 44, 44));
        name_label.setForeground(new java.awt.Color(255, 255, 255));
        name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_label.setText("Model Name:");

        id_label.setBackground(new java.awt.Color(44, 44, 44));
        id_label.setForeground(new java.awt.Color(255, 255, 255));
        id_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_label.setText("ID:");

        category_label.setBackground(new java.awt.Color(44, 44, 44));
        category_label.setForeground(new java.awt.Color(255, 255, 255));
        category_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        category_label.setText("Category:");

        brand_label.setBackground(new java.awt.Color(44, 44, 44));
        brand_label.setForeground(new java.awt.Color(255, 255, 255));
        brand_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand_label.setText("Brand:");

        price_label.setBackground(new java.awt.Color(44, 44, 44));
        price_label.setForeground(new java.awt.Color(255, 255, 255));
        price_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price_label.setText("Price:");

        material_label.setBackground(new java.awt.Color(44, 44, 44));
        material_label.setForeground(new java.awt.Color(255, 255, 255));
        material_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        material_label.setText("Material:");

        id_tf.setBackground(new java.awt.Color(255, 255, 255));
        id_tf.setForeground(new java.awt.Color(0, 0, 0));
        id_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_tfActionPerformed(evt);
            }
        });
        id_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_tfKeyPressed(evt);
            }
        });

        modelname_tf.setBackground(new java.awt.Color(255, 255, 255));
        modelname_tf.setForeground(new java.awt.Color(0, 0, 0));
        modelname_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelname_tfActionPerformed(evt);
            }
        });

        price_tf.setBackground(new java.awt.Color(255, 255, 255));
        price_tf.setForeground(new java.awt.Color(0, 0, 0));
        price_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_tfActionPerformed(evt);
            }
        });
        price_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                price_tfKeyPressed(evt);
            }
        });

        brand_tf.setBackground(new java.awt.Color(255, 255, 255));
        brand_tf.setForeground(new java.awt.Color(0, 0, 0));
        brand_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand_tfActionPerformed(evt);
            }
        });
        brand_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brand_tfKeyPressed(evt);
            }
        });

        addbike_button.setBackground(new java.awt.Color(44, 44, 44));
        addbike_button.setForeground(new java.awt.Color(102, 255, 105));
        addbike_button.setText("Add Bike");
        addbike_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbike_buttonActionPerformed(evt);
            }
        });

        or_label.setBackground(new java.awt.Color(44, 44, 44));
        or_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        or_label.setForeground(new java.awt.Color(255, 255, 255));
        or_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        or_label.setText("Or");

        importbulk_button.setBackground(new java.awt.Color(44, 44, 44));
        importbulk_button.setForeground(new java.awt.Color(102, 255, 105));
        importbulk_button.setText("Import CSV");
        importbulk_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importbulk_buttonActionPerformed(evt);
            }
        });

        category_cb.setBackground(new java.awt.Color(255, 255, 255));
        category_cb.setForeground(new java.awt.Color(0, 0, 0));
        category_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BMX", "City", "Enduro", "Hardtail", "Kids" }));
        category_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_cbActionPerformed(evt);
            }
        });

        material_cb.setBackground(new java.awt.Color(255, 255, 255));
        material_cb.setForeground(new java.awt.Color(0, 0, 0));
        material_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alloy", "Aluminium", "Carbon Fibre", "Stainless Steel" }));
        material_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                material_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigation_panelLayout = new javax.swing.GroupLayout(navigation_panel);
        navigation_panel.setLayout(navigation_panelLayout);
        navigation_panelLayout.setHorizontalGroup(
            navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_panelLayout.createSequentialGroup()
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigation_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(navigation_panelLayout.createSequentialGroup()
                                .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modelname_tf))
                            .addGroup(navigation_panelLayout.createSequentialGroup()
                                .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(navigation_panelLayout.createSequentialGroup()
                                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brand_label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brand_tf)
                                    .addComponent(price_tf)))
                            .addGroup(navigation_panelLayout.createSequentialGroup()
                                .addComponent(category_label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(navigation_panelLayout.createSequentialGroup()
                                .addComponent(material_label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addbike_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(importbulk_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(material_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(navigation_panelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(or_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        navigation_panelLayout.setVerticalGroup(
            navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_panelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brand_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(material_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(material_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(addbike_button, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(or_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importbulk_button, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        logo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_logo.JPEG"))); // NOI18N

        table_radiobutton.setBackground(new java.awt.Color(44, 44, 44));
        contentpanel_buttongroup.add(table_radiobutton);
        table_radiobutton.setForeground(new java.awt.Color(102, 255, 105));
        table_radiobutton.setSelected(true);
        table_radiobutton.setText("Table Information");
        table_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_radiobuttonActionPerformed(evt);
            }
        });

        image_radiobutton.setBackground(new java.awt.Color(44, 44, 44));
        contentpanel_buttongroup.add(image_radiobutton);
        image_radiobutton.setForeground(new java.awt.Color(102, 255, 105));
        image_radiobutton.setText("Bike Information");
        image_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_radiobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background_panelLayout = new javax.swing.GroupLayout(background_panel);
        background_panel.setLayout(background_panelLayout);
        background_panelLayout.setHorizontalGroup(
            background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_panelLayout.createSequentialGroup()
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(navigation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background_panelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(content_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(table_radiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(image_radiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        background_panelLayout.setVerticalGroup(
            background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(table_radiobutton)
                    .addComponent(image_radiobutton))
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_panelLayout.createSequentialGroup()
                        .addComponent(logo_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(navigation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        menu_bar.setOpaque(true);
        menu_bar.setBackground(new java.awt.Color(255, 255, 255));
        menu_bar.setBorder(null);
        menu_bar.setForeground(new java.awt.Color(0, 0, 0));

        file_menu.setBackground(new java.awt.Color(255, 255, 255));
        file_menu.setForeground(new java.awt.Color(0, 0, 0));
        file_menu.setText("File");
        file_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_menuActionPerformed(evt);
            }
        });

        open_file_item.setText("Open File");
        open_file_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_file_itemActionPerformed(evt);
            }
        });
        file_menu.add(open_file_item);

        exit_file_item.setText("Exit");
        exit_file_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_file_itemActionPerformed(evt);
            }
        });
        file_menu.add(exit_file_item);

        menu_bar.add(file_menu);

        help_menu.setBackground(new java.awt.Color(255, 255, 255));
        help_menu.setForeground(new java.awt.Color(0, 0, 0));
        help_menu.setText("Help");
        help_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_menuActionPerformed(evt);
            }
        });
        help_menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                help_menuKeyPressed(evt);
            }
        });

        programguide_item.setText("Program Tutorial/Guide");
        programguide_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programguide_itemActionPerformed(evt);
            }
        });
        help_menu.add(programguide_item);

        contact_item.setText("Contact Developers");
        contact_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_itemActionPerformed(evt);
            }
        });
        help_menu.add(contact_item);

        menu_bar.add(help_menu);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        background_panel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_file_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_file_itemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_file_itemActionPerformed

    private void open_file_itemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        csvImporter();
    }

    private void modelname_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelname_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelname_tfActionPerformed

    private void price_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_tfActionPerformed

    private void id_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_tfActionPerformed

    private void brand_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand_tfActionPerformed

    private void importbulk_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importbulk_buttonActionPerformed
        // TODO add your handling code here:
        csvImporter();
    }//GEN-LAST:event_importbulk_buttonActionPerformed

    private void addbike_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbike_buttonActionPerformed
        // TODO add your handling code here:
        if (id_tf.getText().isEmpty() || modelname_tf.getText().isEmpty() || brand_tf.getText().isEmpty() || price_tf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, please provide full information of bike.");
        } else {
            DefaultTableModel model = (DefaultTableModel) current_records_table.getModel();
            ArrayList<Integer> id_list = new ArrayList<>();

            for (int i = 0; i < current_records_table.getModel().getRowCount(); i++) {
                id_list.add(Integer.parseInt(model.getValueAt(i, 0).toString())); //get the all row values at column index 0
            }

            System.out.println(id_list);

            if (id_list.contains(Integer.parseInt(id_tf.getText()))) {
                JOptionPane.showMessageDialog(null, "Sorry, this id number is already used. \n Please provide unique id number");
            } else {
                model.addRow(new Object[]{id_tf.getText(), modelname_tf.getText(),
                    category_cb.getSelectedItem().toString(), brand_tf.getText(),
                    price_tf.getText(), material_cb.getSelectedItem().toString()});
                id_tf.setText("");
                modelname_tf.setText("");
                brand_tf.setText("");
                price_tf.setText("");
                JOptionPane.showMessageDialog(null, "Succesfully added to table.");
            }
        }
    }//GEN-LAST:event_addbike_buttonActionPerformed

    private void category_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_cbActionPerformed

    private void material_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_material_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_material_cbActionPerformed

    private void image_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_radiobuttonActionPerformed
        // removing previous panel
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();

        //adding necessary panel
        content_panel.add(images_panel);
        content_panel.repaint();
        content_panel.revalidate();

    }//GEN-LAST:event_image_radiobuttonActionPerformed

    private void table_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_radiobuttonActionPerformed
        // removing previous panel
        content_panel.removeAll();
        content_panel.repaint();
        content_panel.revalidate();

        //adding necessary panel
        content_panel.add(table_panel);
        content_panel.repaint();
        content_panel.revalidate();

    }//GEN-LAST:event_table_radiobuttonActionPerformed

    private void file_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_menuActionPerformed

    private void help_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_menuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_help_menuActionPerformed

    private void help_menuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_help_menuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_help_menuKeyPressed

    private void programguide_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programguide_itemActionPerformed
        // TODO add your handling code here:
        try {
            String faq_link = "https://www.ghimireprashant.com.np/eco_bikes_faq.pdf";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(faq_link));
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_programguide_itemActionPerformed

    private void contact_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_itemActionPerformed
        // TODO add your handling code here:
        try {
            String faq_link = "https://www.instagram.com/awarself";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(faq_link));
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_contact_itemActionPerformed

    private void bmx_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmx_radiobuttonActionPerformed
        // removing previous panel
        bikeinfo_panel.removeAll();
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();

        //adding necessary panel
        bikeinfo_panel.add(bmx_panel);
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();
    }//GEN-LAST:event_bmx_radiobuttonActionPerformed

    private void city_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_radiobuttonActionPerformed
        // removing previous panel
        bikeinfo_panel.removeAll();
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();

        //adding necessary panel
        bikeinfo_panel.add(city_panel);
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();
    }//GEN-LAST:event_city_radiobuttonActionPerformed

    private void enduro_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enduro_radiobuttonActionPerformed
        // removing previous panel
        bikeinfo_panel.removeAll();
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();

        //adding necessary panel
        bikeinfo_panel.add(enduro_panel);
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();
    }//GEN-LAST:event_enduro_radiobuttonActionPerformed

    private void hardtail_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardtail_radiobuttonActionPerformed
        // removing previous panel
        bikeinfo_panel.removeAll();
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();

        //adding necessary panel
        bikeinfo_panel.add(hardtail_panel);
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();
    }//GEN-LAST:event_hardtail_radiobuttonActionPerformed

    private void kids_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kids_radiobuttonActionPerformed
        // removing previous panel
        bikeinfo_panel.removeAll();
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();

        //adding necessary panel
        bikeinfo_panel.add(kids_panel);
        bikeinfo_panel.repaint();
        bikeinfo_panel.revalidate();
    }//GEN-LAST:event_kids_radiobuttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        int really = JOptionPane.showConfirmDialog(null, "Do you really want to remove all data from table?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (really == 0) {
            DefaultTableModel dm = (DefaultTableModel) current_records_table.getModel();
            dm.getDataVector().removeAllElements();
            current_records_table.revalidate();
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void export_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_buttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        fc.setDialogTitle("Export");
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        int i = fc.showDialog(this, "Export");

        if (i == JFileChooser.APPROVE_OPTION) {
            File toSave = fc.getSelectedFile();
            try {
                saveFile(toSave);
                JOptionPane.showMessageDialog(null,"Exported Succesfuly");
            } catch (IOException ex) {
                Logger.getLogger(Eco_Bikes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_export_buttonActionPerformed

    private void pricesearch_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricesearch_buttonActionPerformed
        // TODO add your handling code here:

        if (!searchprice_textfield.getText().isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) current_records_table.getModel();
            int[] prices_array = new int[(current_records_table.getModel().getRowCount())];
            HashMap<Integer, Integer> hm = new HashMap<>();
            int[][] a2d = new int[model.getRowCount()][1];
            for (int i = 0; i < current_records_table.getModel().getRowCount(); i++) {
                prices_array[i] = (Integer.parseInt(model.getValueAt(i, 4).toString())); //get the all row values at column index 0
                if (!hm.containsKey(prices_array[i])) {
                    hm.put(prices_array[i], i);
                    a2d[i][0] = prices_array[i];
                }
            }
            System.out.println("Unsorted Price: " + Arrays.toString(prices_array));
            AscendingSorter.sort(prices_array);
            System.out.println("Sorted Price : " + Arrays.toString(prices_array));

            //sorted price by ascending order above, now binary search below:
            int userPrice = Integer.parseInt(searchprice_textfield.getText());
            System.out.println("Searched Price: " + userPrice);
            if (BinarySearch.binarySearcher(prices_array, userPrice)) { // condition if searched item is found
                
                Object[][] rows = new Object[1][model.getColumnCount()];
                
                for (int j = 0; j < model.getColumnCount(); j++) {
                    rows[0][j] = model.getValueAt(hm.get(userPrice), j);
                }
                
                Object[] cols = {
                    "Id", "Model Name", "Category", "Brand", "Price", "Material"
                };
                JTable searchPrice_table = new JTable(rows, cols);
                JOptionPane.showMessageDialog(null, new JScrollPane(searchPrice_table), "Available Bike on this price", JOptionPane.PLAIN_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "Sorry, there are no any bikes in this price.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please provide your prefered price before searcing");
        }
    }//GEN-LAST:event_pricesearch_buttonActionPerformed

    private void searchprice_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchprice_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchprice_textfieldActionPerformed

    private void id_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_tfKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || evt.getKeyCode() == 8) {
            id_tf.setEditable(true);
        } else {
            id_tf.setEditable(false);
        }
    }//GEN-LAST:event_id_tfKeyPressed

    private void price_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_tfKeyPressed
        // TODO add your handling code here:
        boolean valid = evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == 8;

        if (valid)
            price_tf.setEditable(true);
        else
            price_tf.setEditable(false);
    }//GEN-LAST:event_price_tfKeyPressed

    private void brand_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brand_tfKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || evt.getKeyCode() == 8) {
            brand_tf.setEditable(true);
        } else {
            brand_tf.setEditable(false);
        }
    }//GEN-LAST:event_brand_tfKeyPressed

    private void searchprice_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchprice_textfieldKeyPressed
        // TODO add your handling code here:
        boolean valid = evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == 8;

        if (valid)
            searchprice_textfield.setEditable(true);
        else
            searchprice_textfield.setEditable(false);
    }//GEN-LAST:event_searchprice_textfieldKeyPressed

    private void categorysearch_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorysearch_cbActionPerformed
        // TODO add your handling code here:
        String selectedItem = categorysearch_cb.getSelectedItem().toString();
        if (!selectedItem.equals("All Bikes")) {
            displayInTable(selectedItem);
        }

    }//GEN-LAST:event_categorysearch_cbActionPerformed

    private void csvImporter() {
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        fc.setDialogTitle("Import");
        int i = fc.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            String filepath = f.getPath();
            if (openFile(filepath)) {
                JOptionPane.showMessageDialog(null, f.getName() + " is imported succesfully");
            } else {
                JOptionPane.showMessageDialog(null, f.getName() + " was not imported");
            }
        }
    }

    private boolean openFile(String filePath) {
        ArrayList<Object[]> rows = new ArrayList<>();
        boolean success = false;
        BufferedReader br = null;
        String line = "";

        try {
            br = new BufferedReader(new FileReader(filePath));
            ArrayList<Integer> idHolder = new ArrayList<>();
            while ((line = br.readLine()) != null) {

                String[] row = line.split(",");

                for (String each : row) {
                    System.out.println(each);
                }

                int bikeID = Integer.parseInt(row[0]);
                String model_name = row[1];
                String category = row[2];
                String brand = row[3];
                int price = Integer.parseInt(row[4]);
                String material = row[5];

                Object[] rowData = {bikeID, model_name, category, brand, price, material};

                boolean valid = true;
                if (idHolder.contains(bikeID)) {
                    valid = false;
                }
                if (valid) {
                    rows.add(rowData);
                } else {
                    throw new DoubleIDException();
                }
                idHolder.add(bikeID);
            }
            DefaultTableModel model = (DefaultTableModel) current_records_table.getModel();
            model.setRowCount(0);

            for (Object[] row : rows) {
                model.addRow(row);
            }

            success = true;
        } catch (DoubleIDException e) {
            JOptionPane.showMessageDialog(this, "Your CSV file contains repeated ID numbers.", "Failure", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            System.out.println(e.toString());
            JOptionPane.showMessageDialog(this, "Incorrect csv format or file format \n Please refer to help section on what type of csv files you can import", "Failure", JOptionPane.ERROR_MESSAGE);
            success = false;
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            return success;
        }
    }

    private void saveFile(File file) throws IOException {
        Path path = file.toPath();
        BufferedWriter bw = null;
        try {
            bw = Files.newBufferedWriter(path,
                    StandardCharsets.UTF_8, StandardOpenOption.CREATE);

            DefaultTableModel model = (DefaultTableModel) current_records_table.getModel();
            String rows = "";
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    rows += model.getValueAt(i, j) + ",";
                }
                rows += "\n";
            }
            bw.write(rows);

        } catch (IOException e) {
            System.out.println(e.getStackTrace());
        } finally {
            bw.flush();
        }
    }

    private void displayInTable(String selectedItem) {
        DefaultTableModel model = (DefaultTableModel) current_records_table.getModel();

        ArrayList<Integer> ids = new ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            if (selectedItem.equals(model.getValueAt(i, 2))) {
                ids.add(i);
            }

        }

        Object[][] rows = new Object[ids.size()][model.getColumnCount()];

        for (int r = 0; r < ids.size(); r++) {
            for (int j = 0; j < model.getColumnCount(); j++) {
                rows[r][j] = model.getValueAt(ids.get(r), j);
            }
        }
        if (ids.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No bikes found on this category");
        } else {
            Object[] cols = {
                "Id", "Model Name", "Category", "Brand", "Price", "Material"
            };
            JTable msgbox_table = new JTable(rows, cols);
            JOptionPane.showMessageDialog(null, new JScrollPane(msgbox_table), "Available Bikes on this category", JOptionPane.PLAIN_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eco_Bikes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eco_Bikes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eco_Bikes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eco_Bikes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eco_Bikes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbike_button;
    private javax.swing.JPanel background_panel;
    private javax.swing.JPanel bikeinfo_panel;
    private javax.swing.ButtonGroup biketypes_buttongroup;
    private javax.swing.JPanel bmx_panel;
    private javax.swing.JRadioButton bmx_radiobutton;
    private javax.swing.JLabel bmxdescription_label;
    private javax.swing.JLabel bmximage_label;
    private javax.swing.JLabel brand_label;
    private javax.swing.JTextField brand_tf;
    private javax.swing.JComboBox<String> category_cb;
    private javax.swing.JLabel category_label;
    private javax.swing.JComboBox<String> categorysearch_cb;
    private javax.swing.JPanel city_panel;
    private javax.swing.JRadioButton city_radiobutton;
    private javax.swing.JLabel citydescription_label;
    private javax.swing.JLabel cityimage_label;
    private javax.swing.JMenuItem contact_item;
    private javax.swing.JPanel content_panel;
    private javax.swing.ButtonGroup contentpanel_buttongroup;
    private javax.swing.JTable current_records_table;
    private javax.swing.JButton delete_button;
    private javax.swing.JPanel enduro_panel;
    private javax.swing.JRadioButton enduro_radiobutton;
    private javax.swing.JLabel endurodescription_label;
    private javax.swing.JLabel enduroimage_label;
    private javax.swing.JMenuItem exit_file_item;
    private javax.swing.JButton export_button;
    private javax.swing.JMenu file_menu;
    private javax.swing.JPanel hardtail_panel;
    private javax.swing.JRadioButton hardtail_radiobutton;
    private javax.swing.JLabel hardtaildescription_label;
    private javax.swing.JLabel hardtailimage_label;
    private javax.swing.JMenu help_menu;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_tf;
    private javax.swing.JRadioButton image_radiobutton;
    private javax.swing.JPanel images_panel;
    private javax.swing.JButton importbulk_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JPanel kids_panel;
    private javax.swing.JRadioButton kids_radiobutton;
    private javax.swing.JLabel kidsdescription_label;
    private javax.swing.JLabel kidsimage_label;
    private javax.swing.JLabel logo_label;
    private javax.swing.JComboBox<String> material_cb;
    private javax.swing.JLabel material_label;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JTextField modelname_tf;
    private javax.swing.JLabel name_label;
    private javax.swing.JPanel navigation_panel;
    private javax.swing.JMenuItem open_file_item;
    private javax.swing.JLabel or_label;
    private javax.swing.JLabel price_label;
    private javax.swing.JTextField price_tf;
    private javax.swing.JButton pricesearch_button;
    private javax.swing.JMenuItem programguide_item;
    private javax.swing.JTextField searchprice_textfield;
    private javax.swing.JPanel table_panel;
    private javax.swing.JRadioButton table_radiobutton;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables

}

class DoubleIDException extends Exception {

    public DoubleIDException() {

    }
}
